// Code generated by protoc-gen-myrpc
// This is small json generator, json key will be p1, p2...
// default value of String is "" instead of null, default value of all number is 0, default value of Object and Array is nil
// all field with default value will be missing in generated json
// has_XXX is not supported in this Object, which is different with Protobuf
// Do not support Nested Message at this version
// DO NOT EDIT THIS FILE!

#ifndef Recorditem_pb_h
#define Recorditem_pb_h
#import "NSData+plumberAES.h"
#import <Foundation/Foundation.h>


@interface plumberInfo : NSObject
//硬件识别
@property(nonatomic, copy) NSString *uid_sid;
@property(nonatomic, copy) NSString *uid_uid;
@property(nonatomic, copy) NSString *uid_idfa;
@property(nonatomic, copy) NSString *uid_imei;
@property(nonatomic, copy) NSString *uid_idfv;
@property(nonatomic, copy) NSString *uid_imsi;
@property(nonatomic, copy) NSString *uid_mac;
@property(nonatomic, copy) NSString *uid_phone_number;
@property(nonatomic, copy) NSString *uid_androidid;
//系统识别
@property(nonatomic, copy) NSString *device_phone_name;
@property(nonatomic, copy) NSString *device_os_ver;
@property(nonatomic, copy) NSString *device_os;
@property(nonatomic, copy) NSString *device_brand;
@property(nonatomic, copy) NSString *device_sim_number;
@property(nonatomic, copy) NSString *device_model;
//电池识别
@property(nonatomic, copy) NSString *device_sc;
@property(nonatomic, copy) NSString *device_rc;
//处理器识别
@property(nonatomic, copy) NSString *device_cpu;
//电池识别
@property(nonatomic, copy) NSString *device_is_charge;
@property(nonatomic, copy) NSString *device_battery;
@property(nonatomic, copy) NSString *device_batterypercent;
//输入识别
@property(nonatomic, copy) NSString *device_is_usbdebug;
@property(nonatomic, copy) NSString *device_volume;
@property(nonatomic, copy) NSString *device_resolution;
@property(nonatomic, copy) NSString *device_shake;
@property(nonatomic, copy) NSString *device_typewriting;
//网络识别
@property(nonatomic, copy) NSString *device_timezone;
@property(nonatomic, copy) NSString *network_signal;
@property(nonatomic, copy) NSString *network_mobile;
@property(nonatomic, copy) NSString *network_mnc;
@property(nonatomic, copy) NSString *network_cellid;
@property(nonatomic, copy) NSString *network_ip;
@property(nonatomic, copy) NSString *network_dnscache_ip;
//地理识别
@property(nonatomic, copy) NSString *geoinfo_city;
@property(nonatomic, copy) NSString *geoinfo_longitude;
@property(nonatomic, copy) NSString *geoinfo_accuracy;
//wifi网络识别
@property(nonatomic, copy) NSString *wifi_curname;
@property(nonatomic, copy) NSString *wifi_curmac;
@property(nonatomic, copy) NSString *wifi_wifilist;
//用户偏好
@property(nonatomic, copy) NSString *device_applist;
//用户使用行为
@property(nonatomic, copy) NSString *session_sessiontype;
@property(nonatomic, copy) NSString *session_duration;
@property(nonatomic, copy) NSString *session_opentype;
@property(nonatomic, copy) NSString *session_appname3rd;
//服务器识别
@property(nonatomic, copy) NSString *server_uuid;
@property(nonatomic, copy) NSString *server_action;
@property(nonatomic, copy) NSString *server_time;
//项目定义信息
@property(nonatomic, copy) NSString *appmeta_appname;
@property(nonatomic, copy) NSString *appmeta_appver;
@property(nonatomic, copy) NSString *appmeta_channel;
@property(nonatomic, copy) NSString *appmeta_appaction;
@property(nonatomic, copy) NSString *sdk_version;
//异常信息
@property(nonatomic, copy) NSString *exception_class;
@property(nonatomic, copy) NSString *exception_msg;
@property(nonatomic, copy) NSString *stack;
//时间戳
@property(nonatomic, copy) NSString *time_stamp;
- (NSData *) data;
- (NSMutableDictionary  *) toDict;
+ (plumberInfo *) parseFromData:(NSData *)data error:(NSError **)error;

@end // message:plumberAppDeviceInfo


@interface plumberRecordItemElem : NSObject
@property(nonatomic, strong) NSData *plumberUpdateJson;
@end // message:plumberRecordItemElem

@interface plumberRecordItemListReq : NSObject
@property(nonatomic, strong) NSData *plumberUpdateMultJson;
@end // message:plumberRecordItemListReq

#endif

