#source 'https://gitee.com/mirrors/CocoaPods-Specs'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'sixrandom' do
  config = use_native_modules!

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNCPicker', :path => '../node_modules/@react-native-picker/picker'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  target 'sixrandomTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end
